Add implementation of tasks main panel to DG
AY2223S1-CS2103T-T12-2/tp pull request #85
Opened 2022-10-21 09:43 UTC by yunruu

# Issues
- Resolves #75

2022-10-21 10:04 UTC, Santosh3007 requested changes

2022-10-21 10:04 UTC, Santosh3007 commented on docs/DeveloperGuide.md
> +| `* *`    | user           | list all tasks   | to locate details of all the tasks immediately                 |
Maybe you can shift the alignment to match the other lines just for readability :)
```suggestion
| `* *`    | user           | list all tasks        | to locate details of all the tasks immediately                              |
```

2022-10-21 13:19 UTC, jasonqiu212 approved these changes

2022-10-22 06:07 UTC, peppapighs approved these changes
LGTM

2022-10-22 09:14 UTC, Santosh3007 approved these changes
LGTM

2022-10-22 09:14 UTC, merged